# Generated by Django 3.1.2 on 2021-06-17 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20210617_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebookid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
