# Generated by Django 3.1.2 on 2021-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_book_ebookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ebookid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
